name: Deploy to Github Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]
    
jobs:
  build:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v2
    
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.*
      
      # publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        working-directory: ./QEBSPEditor
        run: dotnet publish QEBSPEditor.csproj -c Release -o release --nologo
        
      # build the pages artifact
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./QEBSPEditor/release/wwwroot
          
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
